### ISSUE TITLE
[BUG] Application error when interacting with the player on Android

### ISSUE THREAD

**Issue by SebiderSushi** [Web-SyncPlay/Web-SyncPlay#12] opened 2022-12-21 16:56 UTC
### Reproduction steps
 - Join a room
 - Tap any of the controls in the video player or the playlist

### Reproduction environment
LineageOS 15.1 (Android 8.1.0)
 - Chromium 108.0.5359.156 ([build from the bromite project](https://github.com/bromite/chromium/releases))
 - Firefox for Android 108.1.0 ([build from F-Droid](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/))

<details><summary><b>Console Log</b></summary><pre>
Trying to join room wymn
Established ws connection to io server ZKlrnHZPDq22wFSnAAI2
Not ready yet...
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://web-syncplay.de').
React-Player is ready
Not in sync, seeking to 3.246999979019165
Internal player: {current: P}
Unloading cc of youtube player
Prevent default touch start
Unable to preventDefault inside passive event listener invocation.
TypeError: this is not a Date object.                                         framework-5f4595e5518b5600.js:1
    at getTime (<anonymous>)
    at so (framework-5f4595e5518b5600.js:1:60187)
    at co (framework-5f4595e5518b5600.js:1:60641)
    at Object.useState (framework-5f4595e5518b5600.js:1:66579)
    at t.useState (framework-5f4595e5518b5600.js:1:125433)
    at l ([id]-c3e0dd1c96b5a8f3.js:1:1445)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Wo (framework-5f4595e5518b5600.js:1:68979)
    at Ku (framework-5f4595e5518b5600.js:1:112703)
    at Li (framework-5f4595e5518b5600.js:1:98953)
TypeError: this is not a Date object.                                         main-d719a31ca00eb19c.js:1
    at getTime (<anonymous>)
    at so (framework-5f4595e5518b5600.js:1:60187)
    at co (framework-5f4595e5518b5600.js:1:60641)
    at Object.useState (framework-5f4595e5518b5600.js:1:66579)
    at t.useState (framework-5f4595e5518b5600.js:1:125433)
    at l ([id]-c3e0dd1c96b5a8f3.js:1:1445)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Wo (framework-5f4595e5518b5600.js:1:68979)
    at Ku (framework-5f4595e5518b5600.js:1:112703)
    at Li (framework-5f4595e5518b5600.js:1:98953)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
</pre></details>

**Comment by Yasamato** [comment] 2023-02-11 15:47
Thanks to @puhoshville in #15, this error should be fixed now. Could you please verify that the issue is not persistent anymore?

**Closed as completed by Yasamato** 2023-02-11 15:47 UTC
Labels: bug

**Comment by SebiderSushi** [comment] 2023-02-11 21:59
Issue is fixed :+1:
